name: Echo issue

on:
    issues:
        types: [opened]

jobs:
    new-issue:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello new issue, ${{ github.event.issue.title }}!"